version: '3.8'
volumes: 
  localdb:
services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
    ports: 
      - "3306:3306"
    volumes: 
     - "localdb:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8081:80"